<?php

/*
|--------------------------------------------------------------------------
| Special Sundays catalog (data-driven, versioned)
|--------------------------------------------------------------------------
|
| Source of truth for observances that bias sermon + worship selection during
| their active window ([Sunday − 2 days .. Sunday end-of-day], i.e. Fri 00:00 →
| Sun 23:59). `php artisan db:seed --class=SpecialSundaySeeder` upserts these
| rows into the `special_sundays` table by `key`; editing this file and
| re-seeding is the supported way to add/adjust observances per region without
| a migration. See README "Adding a special Sunday".
|
| DATES ARE NEVER HARDCODED. Each entry carries a rule that resolves to an
| actual Sunday for any given year (see App\Models\SpecialSunday):
|
|   rule_type = 'nth_weekday'   rule = {month:1-12, weekday:0-6 (0=Sun), nth:±1..5}
|                               nth < 0 counts from the end (last = -1).
|   rule_type = 'easter_offset' rule = {offset:int}  days from Western Easter Sunday
|                               (Palm = -7, Pentecost = +49, Easter = 0).
|   rule_type = 'fixed'         rule = {month, day}  a civil/fixed date.
|
| Any anchor that does not already land on a Sunday is snapped to the NEAREST
| Sunday (within ±3 days) so the church observes it on its worship day.
|
| `priority` breaks ties when two windows overlap (higher wins). `region` is an
| optional scope label (null = global); the resolver currently treats it as
| advisory metadata surfaced to the frontend.
|
| All `my`/`td` title + brief text MUST be authored in Myanmar Unicode (never
| Zawgyi); the seeder runs it through normalization and the API guards output.
*/

return [
    'version' => 1,

    'observances' => [

        // ── Liturgical (Revised Common Lectionary, computed from Western Easter) ──
        [
            'key'         => 'palm_sunday',
            'rule_type'   => 'easter_offset',
            'rule'        => ['offset' => -7],
            'titles'      => [
                'en' => 'Palm Sunday',
                'my' => 'စွန်ပလွံခက်နေ့',
                'td' => 'Tum Ni (Palm Sunday)',
                'fr' => 'Dimanche des Rameaux',
                'de' => 'Palmsonntag',
                'es' => 'Domingo de Ramos',
                'ja' => '棕櫚の主日',
                'zh-CN' => '棕枝主日',
                'ko' => '종려주일',
                'hi' => 'खजूर रविवार',
                'ta' => 'குருத்தோலை ஞாயிறு',
                'th' => 'วันอาทิตย์ทางตาล',
                'ar' => 'أحد الشعانين',
                'he' => 'יום ראשון של כפות התמרים',
            ],
            'briefs'      => [
                'en' => 'We welcome the King who comes in humility, waving palms as Jesus enters Jerusalem toward the cross.',
                'my' => 'နှိမ့်ချစွာ ကြွလာတော်မူသော ဘုရင်ကို ကြိုဆိုပါ၏။ ယေရှုသည် ယေရုရှလင်မြို့သို့ ဝင်တော်မူ၏။',
                'td' => 'Kiim takna in hong pai Kumpipa i na kipahpih hi; Jesuh Jerusalem khua sungah a luut ni.',
                'fr' => "Nous accueillons le Roi qui vient dans l'humilité, tandis que Jésus entre à Jérusalem vers la croix.",
                'de' => 'Wir begrüßen den König, der in Demut kommt, während Jesus nach Jerusalem auf das Kreuz zugeht.',
                'es' => 'Recibimos al Rey que viene con humildad, mientras Jesús entra en Jerusalén camino a la cruz.',
                'ja' => 'へりくだって来られる王を迎えます。イエスは十字架へ向かってエルサレムに入られます。',
                'zh-CN' => '我们迎接谦卑而来的君王；耶稣进入耶路撒冷，走向十字架。',
                'ko' => '겸손히 오시는 왕을 맞이합니다. 예수님은 십자가를 향해 예루살렘에 들어가십니다.',
                'hi' => 'हम उस राजा का स्वागत करते हैं जो दीनता में आता है; यीशु क्रूस की ओर यरूशलेम में प्रवेश करते हैं।',
                'ta' => 'தாழ்மையுடன் வருகிற ராஜாவை நாம் வரவேற்கிறோம்; இயேசு சிலுவையை நோக்கி எருசலேமுக்குள் நுழைகிறார்.',
                'th' => 'เราต้อนรับกษัตริย์ผู้เสด็จมาด้วยความถ่อมใจ ขณะที่พระเยซูเสด็จเข้าสู่เยรูซาเล็มมุ่งสู่กางเขน.',
                'ar' => 'نستقبل الملك الآتي بتواضع، إذ يدخل يسوع أورشليم متجها نحو الصليب.',
                'he' => 'אנו מקבלים את המלך הבא בענווה, כאשר ישוע נכנס לירושלים בדרכו אל הצלב.',
            ],
            'sermon_tags' => ['triumphal entry', 'humility', 'kingship', 'palm sunday', 'jerusalem'],
            'music_moods' => ['worship', 'hopeful', 'reverent'],
            'region'      => null,
            'priority'    => 80,
        ],
        [
            'key'         => 'easter_sunday',
            'rule_type'   => 'easter_offset',
            'rule'        => ['offset' => 0],
            'titles'      => [
                'en' => 'Easter Sunday',
                'my' => 'ထမြောက်ရာနေ့ (အီစတာ)',
                'td' => 'Thawhkikni (Easter)',
                'fr' => 'Dimanche de Pâques',
                'de' => 'Ostersonntag',
                'es' => 'Domingo de Pascua',
                'ja' => '復活祭（イースター）',
                'zh-CN' => '复活主日',
                'ko' => '부활주일',
                'hi' => 'पुनरुत्थान रविवार',
                'ta' => 'உயிர்த்தெழுந்த ஞாயிறு',
                'th' => 'วันอาทิตย์อีสเตอร์',
                'ar' => 'أحد القيامة',
                'he' => 'יום ראשון של תחיית המשיח',
            ],
            'briefs'      => [
                'en' => 'Christ is risen! Death is defeated and our living hope is sealed in the empty tomb.',
                'my' => 'ခရစ်တော် ထမြောက်တော်မူပြီ။ သေခြင်းကို အောင်မြင်ပြီး၊ အသက်ရှင်သော မျှော်လင့်ခြင်းကို ရရှိပါ၏။',
                'td' => 'Christ thawhkik hi! Sihna zo a, i nuntakna lametna a hong khinsak hi.',
                'fr' => 'Le Christ est ressuscité ! La mort est vaincue et notre espérance vivante est scellée dans le tombeau vide.',
                'de' => 'Christus ist auferstanden! Der Tod ist besiegt, und unsere lebendige Hoffnung ist im leeren Grab besiegelt.',
                'es' => '¡Cristo ha resucitado! La muerte ha sido vencida y nuestra esperanza viva queda sellada en la tumba vacía.',
                'ja' => 'キリストはよみがえられました。死は打ち破られ、空の墓に生ける希望が示されました。',
                'zh-CN' => '基督已经复活！死亡被击败，空坟墓印证了我们活泼的盼望。',
                'ko' => '그리스도께서 부활하셨습니다. 죽음은 패배했고 빈 무덤 안에 살아 있는 소망이 확증되었습니다.',
                'hi' => 'मसीह जी उठा है! मृत्यु पराजित हुई, और खाली कब्र में हमारी जीवित आशा मुहरबंद है।',
                'ta' => 'கிறிஸ்து உயிர்த்தெழுந்தார்! மரணம் தோற்கடிக்கப்பட்டது; காலியான கல்லறையில் நம்முடைய உயிருள்ள நம்பிக்கை உறுதியாகிறது.',
                'th' => 'พระคริสต์ทรงเป็นขึ้นแล้ว! ความตายพ่ายแพ้ และความหวังที่มีชีวิตของเราถูกยืนยันในอุโมงค์ว่างเปล่า.',
                'ar' => 'المسيح قام! لقد هزمت الموت، وثبت رجاؤنا الحي في القبر الفارغ.',
                'he' => 'המשיח קם! המוות הובס ותקוותנו החיה נחתמה בקבר הריק.',
            ],
            'sermon_tags' => ['resurrection', 'victory', 'empty tomb', 'easter', 'new life'],
            'music_moods' => ['joyful', 'celebrat', 'praise'],
            'region'      => null,
            'priority'    => 100,
        ],
        [
            'key'         => 'pentecost',
            'rule_type'   => 'easter_offset',
            'rule'        => ['offset' => 49],
            'titles'      => [
                'en' => 'Pentecost',
                'my' => 'ပင်တေကုတ္တေနေ့',
                'td' => 'Pentecost Ni',
                'fr' => 'Pentecôte',
                'de' => 'Pfingsten',
                'es' => 'Pentecostés',
                'ja' => 'ペンテコステ',
                'zh-CN' => '圣灵降临主日',
                'ko' => '성령강림주일',
                'hi' => 'पिन्तेकुस्त',
                'ta' => 'பெந்தெகொஸ்தே',
                'th' => 'วันเพ็นเทคอสต์',
                'ar' => 'العنصرة',
                'he' => 'חג השבועות',
            ],
            'briefs'      => [
                'en' => 'The Spirit is poured out and the church is born — fire, wind, and bold witness to the nations.',
                'my' => 'သန့်ရှင်းသောဝိညာဉ်တော် သွန်းလောင်းခြင်းခံရပြီး အသင်းတော် ဖွဲ့စည်းတည်ထောင်ခြင်း ဖြစ်ပါ၏။',
                'td' => 'Kha Siangtho hong sung a, pawlpi piang hi; mei, huihpi, leh hangsanna tetti.',
                'fr' => "L'Esprit est répandu et l'Église naît : feu, vent et témoignage courageux aux nations.",
                'de' => 'Der Geist wird ausgegossen und die Kirche wird geboren: Feuer, Wind und mutiges Zeugnis für die Völker.',
                'es' => 'El Espíritu es derramado y nace la iglesia: fuego, viento y testimonio valiente a las naciones.',
                'ja' => '聖霊が注がれ、教会が生まれました。火と風、そして諸国への大胆な証しの日です。',
                'zh-CN' => '圣灵被浇灌，教会由此诞生；火、风和向万国勇敢作见证同在。',
                'ko' => '성령께서 부어지시고 교회가 태어났습니다. 불과 바람, 그리고 열방을 향한 담대한 증언의 날입니다.',
                'hi' => 'पवित्र आत्मा उंडेला गया और कलीसिया जन्मी — आग, पवन और राष्ट्रों के लिए साहसी गवाही।',
                'ta' => 'பரிசுத்த ஆவி பொழியப்பட்டு சபை பிறக்கிறது — அக்கினி, காற்று, நாடுகளுக்கான தைரியமான சாட்சி.',
                'th' => 'พระวิญญาณบริสุทธิ์ถูกเทลงมาและคริสตจักรถือกำเนิด พร้อมไฟ ลม และคำพยานที่กล้าหาญต่อบรรดาประชาชาติ.',
                'ar' => 'انسكب الروح القدس وولدت الكنيسة: نار وريح وشهادة جريئة للأمم.',
                'he' => 'רוח הקודש נשפכה והקהילה נולדה: אש, רוח ועדות אמיצה לעמים.',
            ],
            'sermon_tags' => ['holy spirit', 'pentecost', 'church', 'power', 'witness'],
            'music_moods' => ['joyful', 'worship', 'praise'],
            'region'      => null,
            'priority'    => 80,
        ],
        [
            'key'         => 'reformation_sunday',
            'rule_type'   => 'nth_weekday',
            'rule'        => ['month' => 10, 'weekday' => 0, 'nth' => -1], // last Sunday of October
            'titles'      => [
                'en' => 'Reformation Sunday',
                'my' => 'ပြုပြင်ပြောင်းလဲရေး တနင်္ဂနွေ',
                'td' => 'Reformation Pathianni',
                'fr' => 'Dimanche de la Réforme',
                'de' => 'Reformationssonntag',
                'es' => 'Domingo de la Reforma',
                'ja' => '宗教改革主日',
                'zh-CN' => '宗教改革主日',
                'ko' => '종교개혁주일',
                'hi' => 'सुधार रविवार',
                'ta' => 'சீர்திருத்த ஞாயிறு',
                'th' => 'วันอาทิตย์แห่งการปฏิรูป',
                'ar' => 'أحد الإصلاح',
                'he' => 'יום ראשון של הרפורמציה',
            ],
            'briefs'      => [
                'en' => 'Saved by grace through faith alone — we remember the recovery of the gospel and the open Word.',
                'my' => 'ယုံကြည်ခြင်းအားဖြင့် ကျေးဇူးတော်ကြောင့်သာ ကယ်တင်ခြင်း — ဧဝံဂေလိတရား ပြန်လည်ထွန်းကားလာခြင်းကို အောက်မေ့ပါ၏။',
                'td' => 'Upna tungtawn hehpihna in hotkhiatna — lungdamna thu kiphuankikna i phawk hi.',
                'fr' => "Sauvés par la grâce au moyen de la foi seule, nous nous souvenons de l'Évangile retrouvé et de la Parole ouverte.",
                'de' => 'Aus Gnade durch Glauben allein gerettet, erinnern wir uns an die Wiederentdeckung des Evangeliums und des offenen Wortes.',
                'es' => 'Salvos por gracia mediante la fe sola, recordamos la recuperación del evangelio y la Palabra abierta.',
                'ja' => '信仰によって、恵みにより救われます。福音と開かれた御言葉の回復を覚えます。',
                'zh-CN' => '我们因信、靠恩典得救；今日记念福音的恢复和向人打开的圣言。',
                'ko' => '오직 믿음으로, 은혜로 구원받음을 기억하며 복음과 열린 말씀의 회복을 되새깁니다.',
                'hi' => 'केवल विश्वास के द्वारा अनुग्रह से उद्धार — हम सुसमाचार की पुनर्प्राप्ति और खुले वचन को स्मरण करते हैं।',
                'ta' => 'விசுவாசத்தின் மூலம் கிருபையால் இரட்சிப்பு — சுவிசேஷத்தின் மீட்பையும் திறந்த வார்த்தையையும் நினைவுகூர்கிறோம்.',
                'th' => 'รับความรอดโดยพระคุณทางความเชื่อเท่านั้น เราระลึกถึงการฟื้นคืนข่าวประเสริฐและพระวจนะที่เปิดเผย.',
                'ar' => 'الخلاص بالنعمة بالإيمان وحده؛ نتذكر استعادة الإنجيل والكلمة المفتوحة للجميع.',
                'he' => 'ישועה בחסד על ידי אמונה בלבד; אנו זוכרים את השבת הבשורה ואת הדבר הפתוח.',
            ],
            'sermon_tags' => ['grace', 'faith', 'gospel', 'scripture', 'reformation'],
            'music_moods' => ['worship', 'reverent', 'hopeful'],
            'region'      => null,
            'priority'    => 60,
        ],
        [
            'key'         => 'advent_first',
            'rule_type'   => 'fixed',
            'rule'        => ['month' => 11, 'day' => 30], // St Andrew's Day anchor; snaps to the nearest Sunday = Advent 1
            'titles'      => [
                'en' => 'First Sunday of Advent',
                'my' => 'အဒ်ဗင့် ပထမတနင်္ဂနွေ',
                'td' => 'Advent Pathianni Masapen',
                'fr' => "Premier dimanche de l'Avent",
                'de' => 'Erster Adventssonntag',
                'es' => 'Primer domingo de Adviento',
                'ja' => '待降節第一主日',
                'zh-CN' => '将临期第一主日',
                'ko' => '대림절 첫째 주일',
                'hi' => 'आगमन का पहला रविवार',
                'ta' => 'ஆகமனத்தின் முதல் ஞாயிறு',
                'th' => 'อาทิตย์แรกแห่งเทศกาลเตรียมรับเสด็จ',
                'ar' => 'الأحد الأول من المجيء',
                'he' => 'יום ראשון הראשון של הציפייה לבוא המשיח',
            ],
            'briefs'      => [
                'en' => 'We begin the season of waiting — hope kindled as we prepare our hearts for the coming of Christ.',
                'my' => 'စောင့်မျှော်ခြင်းကာလ စတင်ပါ၏။ ခရစ်တော် ကြွလာတော်မူခြင်းအတွက် နှလုံးသားကို ပြင်ဆင်ရင်း မျှော်လင့်ခြင်း ထွန်းလင်းပါ၏။',
                'td' => 'Ngakna hun i kipan; Christ hongpaina ading i lungtang kiginkholhna lametna hong tang hi.',
                'fr' => "Nous entrons dans le temps de l'attente : l'espérance s'allume tandis que nous préparons nos coeurs à la venue du Christ.",
                'de' => 'Wir beginnen die Zeit des Wartens: Hoffnung wird entzündet, während wir unsere Herzen auf das Kommen Christi vorbereiten.',
                'es' => 'Comenzamos el tiempo de espera: la esperanza se enciende mientras preparamos el corazón para la venida de Cristo.',
                'ja' => '待ち望む季節が始まります。キリストの来臨に心を備えながら、希望の灯がともります。',
                'zh-CN' => '我们进入等候的季节；预备心迎接基督来临时，盼望被重新点燃。',
                'ko' => '기다림의 절기를 시작합니다. 그리스도의 오심을 위해 마음을 준비하며 소망이 다시 타오릅니다.',
                'hi' => 'हम प्रतीक्षा के मौसम की शुरुआत करते हैं — मसीह के आगमन के लिए हृदय तैयार करते हुए आशा फिर जल उठती है।',
                'ta' => 'காத்திருக்கும் காலத்தை நாம் தொடங்குகிறோம் — கிறிஸ்துவின் வருகைக்குத் இதயத்தை ஆயத்தப்படுத்தும்போது நம்பிக்கை மீண்டும் பற்றுகிறது.',
                'th' => 'เราเริ่มต้นฤดูกาลแห่งการรอคอย ความหวังถูกจุดขึ้นอีกครั้งขณะเตรียมหัวใจรับการเสด็จมาของพระคริสต์.',
                'ar' => 'نبدأ موسم الانتظار؛ يشتعل الرجاء من جديد ونحن نهيئ قلوبنا لمجيء المسيح.',
                'he' => 'אנו מתחילים את עונת ההמתנה; התקווה נדלקת מחדש כאשר אנו מכינים את לבנו לבוא המשיח.',
            ],
            'sermon_tags' => ['advent', 'hope', 'waiting', 'preparation', 'incarnation'],
            'music_moods' => ['hopeful', 'reverent', 'peace'],
            'region'      => null,
            'priority'    => 60,
        ],

        // ── Civil observances (editable per region; snap to the worship Sunday) ──
        [
            'key'         => 'mothers_day',
            'rule_type'   => 'nth_weekday',
            'rule'        => ['month' => 5, 'weekday' => 0, 'nth' => 2], // 2nd Sunday of May
            'titles'      => [
                'en' => "Mother's Day",
                'my' => 'အမေများနေ့',
                'td' => 'Nu Ni (Mother\'s Day)',
                'fr' => 'Fête des mères',
                'de' => 'Muttertag',
                'es' => 'Día de las Madres',
                'ja' => '母の日',
                'zh-CN' => '母亲节',
                'ko' => '어머니 주일',
                'hi' => 'मातृ दिवस',
                'ta' => 'அன்னையர் தினம்',
                'th' => 'วันแม่',
                'ar' => 'عيد الأم',
                'he' => 'יום האם',
            ],
            'briefs'      => [
                'en' => 'We give thanks for mothers and the love that nurtures us, honoring them before the Lord today.',
                'my' => 'အမေများနှင့် ကျွန်ုပ်တို့ကို ပြုစုပျိုးထောင်သော မေတ္တာအတွက် ကျေးဇူးတင်ပါ၏။',
                'td' => 'Nu te leh amau itna ading lungdam i ko a, tu ni in Topa maiah i zahtak hi.',
                'fr' => "Nous rendons grâce pour les mères et pour l'amour qui nous nourrit, les honorant aujourd'hui devant le Seigneur.",
                'de' => 'Wir danken für Mütter und für die Liebe, die uns trägt, und ehren sie heute vor dem Herrn.',
                'es' => 'Damos gracias por las madres y por el amor que nos cuida, honrándolas hoy delante del Señor.',
                'ja' => '母たちと、私たちを育む愛に感謝し、今日主の前で敬意を表します。',
                'zh-CN' => '我们为母亲和养育我们的爱献上感谢，今天在主面前尊荣她们。',
                'ko' => '어머니들과 우리를 돌보는 사랑에 감사하며 오늘 주님 앞에서 그들을 존중합니다.',
                'hi' => 'हम माताओं और हमें पोषित करने वाले प्रेम के लिए धन्यवाद देते हैं, और आज प्रभु के सामने उनका आदर करते हैं।',
                'ta' => 'தாய்மார்களுக்கும் நம்மை வளர்க்கும் அன்பிற்கும் நன்றி செலுத்தி, இன்று ஆண்டவரின் முன் அவர்களை மதிக்கிறோம்.',
                'th' => 'เราขอบคุณสำหรับแม่และความรักที่เลี้ยงดูเรา วันนี้เรายกย่องพวกเธอต่อพระพักตร์องค์พระผู้เป็นเจ้า.',
                'ar' => 'نشكر الله من أجل الأمهات والمحبة التي ترعانا، ونكرمهن اليوم أمام الرب.',
                'he' => 'אנו מודים על האמהות ועל האהבה המטפחת אותנו, ומכבדים אותן היום לפני האדון.',
            ],
            'sermon_tags' => ['motherhood', 'family', 'honor your parents', 'love', 'gratitude'],
            'music_moods' => ['grateful', 'love', 'peace'],
            'region'      => null,
            'priority'    => 50,
        ],
        [
            'key'         => 'fathers_day',
            'rule_type'   => 'nth_weekday',
            'rule'        => ['month' => 6, 'weekday' => 0, 'nth' => 3], // 3rd Sunday of June
            'titles'      => [
                'en' => "Father's Day",
                'my' => 'အဖေများနေ့',
                'td' => 'Pa Ni (Father\'s Day)',
                'fr' => 'Fête des pères',
                'de' => 'Vatertag',
                'es' => 'Día de los Padres',
                'ja' => '父の日',
                'zh-CN' => '父亲节',
                'ko' => '아버지 주일',
                'hi' => 'पितृ दिवस',
                'ta' => 'தந்தையர் தினம்',
                'th' => 'วันพ่อ',
                'ar' => 'عيد الأب',
                'he' => 'יום האב',
            ],
            'briefs'      => [
                'en' => 'We honor fathers and the steady, sacrificial love that points us to our Father in heaven.',
                'my' => 'အဖေများနှင့် ကောင်းကင်ဘုံရှိ အဖခမည်းတော်ဆီသို့ ညွှန်ပြသော ခိုင်မြဲသည့် မေတ္တာအတွက် ဂုဏ်ပြုပါ၏။',
                'td' => 'Pa te leh vana i Pa lam hong lak a kician itna i zahtak hi.',
                'fr' => "Nous honorons les pères et l'amour fidèle et sacrificiel qui nous montre notre Père céleste.",
                'de' => 'Wir ehren Väter und die beständige, hingebungsvolle Liebe, die auf unseren Vater im Himmel weist.',
                'es' => 'Honramos a los padres y el amor firme y sacrificial que nos señala a nuestro Padre celestial.',
                'ja' => '父たちと、天の父を指し示す堅く犠牲的な愛を敬います。',
                'zh-CN' => '我们尊荣父亲，也尊荣那坚忍、舍己并指向天父的爱。',
                'ko' => '아버지들과 하늘 아버지를 가리키는 변함없고 희생적인 사랑을 존중합니다.',
                'hi' => 'हम पिताओं और उस स्थिर, बलिदानी प्रेम का आदर करते हैं जो हमें स्वर्गीय पिता की ओर दिखाता है।',
                'ta' => 'தந்தையரையும் பரலோகத் தந்தையை நோக்கிக் காட்டும் உறுதியான, தியாகமுள்ள அன்பையும் நாம் மதிக்கிறோம்.',
                'th' => 'เรายกย่องพ่อและความรักที่มั่นคงเสียสละ ซึ่งชี้เราไปยังพระบิดาในสวรรค์.',
                'ar' => 'نكرم الآباء والمحبة الثابتة الباذلة التي تشير بنا إلى أبينا السماوي.',
                'he' => 'אנו מכבדים את האבות ואת האהבה היציבה והמקריבה המכוונת אותנו אל אבינו שבשמים.',
            ],
            'sermon_tags' => ['fatherhood', 'family', 'honor your parents', 'godly leadership', 'love'],
            'music_moods' => ['grateful', 'strength', 'peace'],
            'region'      => null,
            'priority'    => 50,
        ],
        [
            'key'         => 'childrens_day',
            'rule_type'   => 'fixed',
            'rule'        => ['month' => 6, 'day' => 1], // International Children's Day; snaps to nearest Sunday
            'titles'      => [
                'en' => "Children's Day",
                'my' => 'ကလေးများနေ့',
                'td' => 'Naupang Ni (Children\'s Day)',
                'fr' => 'Journée des enfants',
                'de' => 'Kindertag',
                'es' => 'Día de la Niñez',
                'ja' => '子どもの日',
                'zh-CN' => '儿童节',
                'ko' => '어린이 주일',
                'hi' => 'बाल दिवस',
                'ta' => 'குழந்தைகள் தினம்',
                'th' => 'วันเด็ก',
                'ar' => 'يوم الأطفال',
                'he' => 'יום הילדים',
            ],
            'briefs'      => [
                'en' => 'Let the little children come — we celebrate and bless the youngest among us as a gift from God.',
                'my' => 'ကလေးသူငယ်တို့ ငါ့ထံသို့ လာကြစေ — ဘုရားသခင်၏ ဆုကျေးဇူးအဖြစ် ကလေးများကို ဂုဏ်ပြုကောင်းချီးပေးပါ၏။',
                'td' => 'Naupang te ka kiangah hong pai uhheh — Pasian letsong bangin naupang te i thupha hi.',
                'fr' => 'Laissez venir les petits enfants : nous célébrons et bénissons les plus jeunes parmi nous comme un don de Dieu.',
                'de' => 'Lasst die Kinder kommen: Wir feiern und segnen die Jüngsten unter uns als Gabe Gottes.',
                'es' => 'Dejen que los niños vengan: celebramos y bendecimos a los más pequeños como un regalo de Dios.',
                'ja' => '幼子たちを来させなさい。神からの贈り物として、最も若い人々を祝い祝福します。',
                'zh-CN' => '让小孩子到主这里来；我们庆祝并祝福最年幼的人，他们是神所赐的礼物。',
                'ko' => '어린아이들이 오게 하십시오. 하나님이 주신 선물인 가장 어린 이들을 축복하며 기뻐합니다.',
                'hi' => 'छोटे बच्चों को आने दो — हम अपने सबसे छोटे लोगों को परमेश्वर के उपहार के रूप में मनाते और आशीष देते हैं।',
                'ta' => 'சிறு பிள்ளைகள் வரட்டும் — தேவனுடைய வரமாக நம்மிடையே உள்ள இளையவர்களை நாம் கொண்டாடி ஆசீர்வதிக்கிறோம்.',
                'th' => 'จงให้เด็กเล็ก ๆ มาหาเรา เราเฉลิมฉลองและอวยพรผู้เล็กที่สุดในหมู่เราในฐานะของขวัญจากพระเจ้า.',
                'ar' => 'دعوا الأطفال يأتون؛ نحتفل بأصغر من بيننا ونباركهم كعطية من الله.',
                'he' => 'הניחו לילדים לבוא; אנו חוגגים ומברכים את הצעירים שבינינו כמתנה מאלוהים.',
            ],
            'sermon_tags' => ['children', 'faith like a child', 'blessing', 'family', 'discipleship'],
            'music_moods' => ['joyful', 'hopeful', 'praise'],
            'region'      => null,
            'priority'    => 45,
        ],
        [
            'key'         => 'youth_day',
            'rule_type'   => 'nth_weekday',
            'rule'        => ['month' => 8, 'weekday' => 0, 'nth' => 2], // 2nd Sunday of August (region-editable)
            'titles'      => [
                'en' => 'Youth Day',
                'my' => 'လူငယ်များနေ့',
                'td' => 'Tangval Ni (Youth Day)',
                'fr' => 'Journée de la jeunesse',
                'de' => 'Jugendtag',
                'es' => 'Día de la Juventud',
                'ja' => '青年の日',
                'zh-CN' => '青年主日',
                'ko' => '청년 주일',
                'hi' => 'युवा दिवस',
                'ta' => 'இளைஞர் தினம்',
                'th' => 'วันเยาวชน',
                'ar' => 'يوم الشباب',
                'he' => 'יום הנוער',
            ],
            'briefs'      => [
                'en' => 'We commission the next generation — bold, faithful, and called to let no one despise their youth.',
                'my' => 'နောက်လူမျိုးဆက်ကို တာဝန်ပေးအပ်ပါ၏ — ရဲရင့်၍ သစ္စာရှိစွာ ဘုရားသခင်အတွက် အသက်ရှင်ကြစေ။',
                'td' => 'Khangthak suankhat te i sawl hi — hangsan, muanhuai, kuamah in tangvalna honmusit khол louhna.',
                'fr' => 'Nous envoyons la prochaine génération : courageuse, fidèle et appelée à ne laisser personne mépriser sa jeunesse.',
                'de' => 'Wir senden die nächste Generation aus: mutig, treu und berufen, sich von niemandem wegen ihrer Jugend verachten zu lassen.',
                'es' => 'Comisionamos a la próxima generación: valiente, fiel y llamada a no dejar que nadie menosprecie su juventud.',
                'ja' => '次の世代を送り出します。大胆で忠実に歩み、若さを軽んじられない召しを受けています。',
                'zh-CN' => '我们差遣下一代：勇敢、忠心，并蒙召不让人小看他们年轻。',
                'ko' => '다음 세대를 파송합니다. 담대하고 신실하게, 누구도 그들의 젊음을 업신여기지 못하게 부름받았습니다.',
                'hi' => 'हम अगली पीढ़ी को भेजते हैं — साहसी, विश्वासयोग्य, और इस बुलाहट के साथ कि कोई उनकी जवानी को तुच्छ न समझे।',
                'ta' => 'அடுத்த தலைமுறையை நாம் அனுப்புகிறோம் — தைரியமாய், உண்மையாய், இளமையை யாரும் இகழாதபடி அழைக்கப்பட்டவர்களாய்.',
                'th' => 'เราส่งคนรุ่นต่อไปออกไป ให้กล้าหาญ สัตย์ซื่อ และถูกเรียกไม่ให้ใครดูหมิ่นความหนุ่มสาวของพวกเขา.',
                'ar' => 'نرسل الجيل القادم بشجاعة وأمانة، مدعوين ألا يستخف أحد بحداثتهم.',
                'he' => 'אנו שולחים את הדור הבא באומץ ובנאמנות, קרואים שלא יזלזל איש בנעוריהם.',
            ],
            'sermon_tags' => ['youth', 'calling', 'courage', 'discipleship', 'faithfulness'],
            'music_moods' => ['hopeful', 'joyful', 'strength'],
            'region'      => null,
            'priority'    => 45,
        ],
        [
            'key'         => 'thanksgiving_sunday',
            'rule_type'   => 'nth_weekday',
            'rule'        => ['month' => 11, 'weekday' => 4, 'nth' => 4], // US Thanksgiving (4th Thu Nov); snaps to nearest Sunday
            'titles'      => [
                'en' => 'Thanksgiving Sunday',
                'my' => 'ကျေးဇူးတော်ချီးမွမ်းရာ တနင်္ဂနွေ',
                'td' => 'Lungdam Kohna Pathianni',
                'fr' => "Dimanche d'action de grâce",
                'de' => 'Danksonntag',
                'es' => 'Domingo de Acción de Gracias',
                'ja' => '感謝祭主日',
                'zh-CN' => '感恩主日',
                'ko' => '추수감사주일',
                'hi' => 'धन्यवाद रविवार',
                'ta' => 'நன்றியறிதல் ஞாயிறு',
                'th' => 'วันอาทิตย์แห่งการขอบพระคุณ',
                'ar' => 'أحد الشكر',
                'he' => 'יום ראשון של הודיה',
            ],
            'briefs'      => [
                'en' => 'We count our blessings and give thanks in all things to the God from whom every good gift flows.',
                'my' => 'ကောင်းချီးများကို ရေတွက်၍ အရာရာ၌ ကျေးဇူးတော်ကို ချီးမွမ်းပါ၏။',
                'td' => 'Thupha te i sim a, na tengtengah letsong hoih a hong piakpa Pasian tungah lungdam i ko hi.',
                'fr' => 'Nous comptons nos bénédictions et rendons grâce en toutes choses au Dieu de qui vient tout don parfait.',
                'de' => 'Wir zählen unsere Segnungen und danken in allem dem Gott, von dem jede gute Gabe kommt.',
                'es' => 'Contamos nuestras bendiciones y damos gracias en todo al Dios de quien procede todo buen don.',
                'ja' => '祝福を数え、すべての良い賜物の源である神に、あらゆることの中で感謝します。',
                'zh-CN' => '我们数算恩典，在凡事上感谢那赐下一切美善礼物的神。',
                'ko' => '우리의 복을 헤아리며 모든 좋은 선물을 주시는 하나님께 범사에 감사드립니다.',
                'hi' => 'हम अपनी आशीषों को गिनते हैं और हर अच्छी देन देने वाले परमेश्वर को सब बातों में धन्यवाद देते हैं।',
                'ta' => 'நாம் ஆசீர்வாதங்களை எண்ணி, எல்லா நல்ல வரங்களும் வரும் தேவனுக்கு எல்லாவற்றிலும் நன்றி செலுத்துகிறோம்.',
                'th' => 'เรานับพระพรของเราและขอบพระคุณพระเจ้าในทุกสิ่ง พระองค์ผู้ประทานของประทานดีทุกอย่าง.',
                'ar' => 'نعد بركاتنا ونشكر الله في كل شيء، فهو مصدر كل عطية صالحة.',
                'he' => 'אנו סופרים את ברכותינו ומודים בכל דבר לאלוהים שממנו באה כל מתנה טובה.',
            ],
            'sermon_tags' => ['thanksgiving', 'gratitude', 'provision', 'contentment', 'praise'],
            'music_moods' => ['grateful', 'thankful', 'praise'],
            'region'      => null,
            'priority'    => 55,
        ],
    ],
];
