<script setup>
// AI Pastor Chat — a single-assistant streaming conversation that writes into the
// unified history spine. The reply is generated by the worker and arrives via the
// webhook; we poll the owner-scoped messages endpoint until the assistant turn lands.
// Resumes a prior session when the hash carries ?session=<id>.
import { ref, nextTick, onMounted, onBeforeUnmount } from "vue";
import { useI18n } from "vue-i18n";
import { api } from "../composables/useApi";

const { t } = useI18n();

const messages = ref([]);          // { sender, content }
const draft = ref("");
const sessionId = ref(null);
const waiting = ref(false);
const error = ref("");
const scroller = ref(null);
let poll = null;

// Reply language — locked once the session starts (it is a session property server-side;
// switch languages by starting a new chat). "auto" lets the worker detect from the first
// message. Codes mirror the worker's supported set (driver.py _LANG_NAME).
const LANGUAGES = [
  { code: "auto", label: t("pastor.autoDetect") },
  { code: "en", label: "English" },
  { code: "my", label: "မြန်မာ" },
  { code: "td", label: "Tedim" },
  { code: "cnh", label: "Lai Hakha" },
  { code: "cfm", label: "Falam" },
  { code: "lus", label: "Mizo" },
];
// Default to Auto Detect so typing in any supported language just works; the worker
// detects from the first message and locks it onto the session. Users can still pick a
// specific language explicitly before sending.
const language = ref("auto");

function sessionFromHash() {
  const m = window.location.hash.match(/session=([0-9a-f-]+)/i);
  return m ? m[1] : null;
}

async function scrollDown() {
  await nextTick();
  if (scroller.value) scroller.value.scrollTop = scroller.value.scrollHeight;
}

async function hydrate(id) {
  sessionId.value = id;
  try {
    const res = await api.pastorMessages(id);
    messages.value = res.messages || [];
    scrollDown();
  } catch { error.value = t("pastor.loadError"); }
}

function waitForReply(prevCount) {
  waiting.value = true;
  let tries = 0;
  clearInterval(poll);
  poll = setInterval(async () => {
    tries++;
    try {
      const res = await api.pastorMessages(sessionId.value);
      const msgs = res.messages || [];
      const assistantArrived = msgs.length > prevCount &&
        msgs[msgs.length - 1].sender === "assistant";
      if (assistantArrived || tries > 45) {
        messages.value = msgs;
        waiting.value = false;
        clearInterval(poll);
        scrollDown();
      }
    } catch { /* keep polling */ }
  }, 2000);
}

async function send() {
  const text = draft.value.trim();
  if (!text || waiting.value) return;
  draft.value = "";
  messages.value.push({ sender: "user", content: text });
  scrollDown();
  error.value = "";

  try {
    if (!sessionId.value) {
      await api.ensureSession();
      const res = await api.pastorStart({ message: text, language: language.value });
      sessionId.value = res.session.id;
      // Reflect the session id in the URL so a refresh resumes it.
      history.replaceState(null, "", `#pastor?session=${sessionId.value}`);
    } else {
      await api.pastorPostMessage(sessionId.value, text);
    }
    waitForReply(messages.value.length);
  } catch (e) {
    error.value = e?.body?.message || t("pastor.reachError");
    waiting.value = false;
  }
}

onMounted(async () => {
  await api.ensureSession().catch(() => {});
  const id = sessionFromHash();
  if (id) hydrate(id);
});
onBeforeUnmount(() => clearInterval(poll));
</script>

<template>
  <section class="pastor">
    <header class="pastor-head">
      <h2>💬 {{ t("pastor.title") }}</h2>
      <p>{{ t("pastor.subtitle") }}</p>
      <label class="pastor-lang">
        <span>{{ t("common.language") }}</span>
        <select v-model="language" :disabled="!!sessionId"
          :title="sessionId ? t('pastor.changeLanguageHint') : ''">
          <option v-for="l in LANGUAGES" :key="l.code" :value="l.code">{{ l.label }}</option>
        </select>
      </label>
    </header>

    <div ref="scroller" class="pastor-thread">
      <p v-if="!messages.length" class="pastor-empty">
        {{ t("pastor.empty") }}
      </p>
      <div v-for="(m, i) in messages" :key="i" :class="['bubble', m.sender]">
        <span class="who">{{ m.sender === 'user' ? t('common.you') : t('pastor.role') }}</span>
        <p>{{ m.content }}</p>
      </div>
      <div v-if="waiting" class="bubble assistant typing"><span class="who">{{ t('pastor.role') }}</span><p>…</p></div>
    </div>

    <p v-if="error" class="pastor-err">{{ error }}</p>

    <form class="pastor-input" @submit.prevent="send">
      <textarea v-model="draft" rows="2" :placeholder="t('pastor.placeholder')"
        @keydown.enter.exact.prevent="send"></textarea>
      <button type="submit" :disabled="waiting || !draft.trim()">{{ t("common.send") }}</button>
    </form>
  </section>
</template>

<style scoped>
.pastor { max-width: 760px; margin: 0 auto; padding: 16px; display: flex; flex-direction: column; height: 100%; }
.pastor-head h2 { margin: 0; }
.pastor-head p { opacity: .7; margin: 4px 0 12px; }
.pastor-lang { display: inline-flex; align-items: center; gap: 8px; margin-bottom: 12px; font-size: 13px; }
.pastor-lang span { opacity: .7; }
.pastor-lang select { padding: 5px 8px; border-radius: 8px; border: 1px solid var(--border); background: var(--surface-2); color: var(--text); }
.pastor-lang select:disabled { opacity: .6; cursor: not-allowed; }
.pastor-thread { flex: 1; overflow-y: auto; min-height: 320px; padding: 8px;
  border: 1px solid var(--border); border-radius: 12px; background: var(--surface); color: var(--text); }
.pastor-empty { opacity: .6; text-align: center; margin-top: 40px; }
.bubble { max-width: 80%; margin: 8px 0; padding: 8px 12px; border-radius: 12px; }
.bubble .who { font-size: 11px; opacity: .6; }
.bubble p { margin: 2px 0 0; white-space: pre-wrap; line-height: 1.45; }
.bubble.user { margin-left: auto; background: var(--primary); color: var(--on-primary); }
.bubble.assistant { margin-right: auto; background: var(--surface-2); color: var(--text); }
.bubble.typing p { letter-spacing: 2px; }
.pastor-err { color: var(--danger); font-size: 13px; }
.pastor-input { display: flex; gap: 8px; margin-top: 10px; }
.pastor-input textarea { flex: 1; resize: none; padding: 8px 10px; border-radius: 10px; border: 1px solid var(--border); background: var(--surface-2); color: var(--text); }
.pastor-input textarea::placeholder { color: var(--text-faint); }
.pastor-input button { padding: 0 18px; border-radius: 10px; border: none; background: var(--primary); color: var(--on-primary); cursor: pointer; }
.pastor-input button:disabled { opacity: .5; cursor: default; }
</style>
