"""
LLM engine — turns the logged-in user's intake (name, mood, prayer text) into the
spoken content of the service: opening prayer, scripture selection, sermon, and
benediction. The user's own words drive every segment, so no two services match.

Scripture text is NOT generated by the model (copyright + accuracy). The model only
chooses a reference; full verse text is resolved separately via a licensed Bible API.
"""

from __future__ import annotations

import json
import os
import re

import requests


def _strip_formatting(text: str) -> str:
    """Reduce model output to clean spoken prose.

    Free models tend to dress a sermon up as a *script* — markdown headings, bold,
    bullet lists, horizontal rules, and bracketed stage directions like
    ``**[Soft instrumental intro]**`` or ``[Pause - 3 seconds]``. None of that should
    be shown to (or read aloud to) the worshipper, so we strip it here, leaving the
    words. Applied to every spoken segment, so the prompt and the model can't leak
    formatting into the service."""
    # Stage directions / cues in brackets, with any wrapping emphasis: **[...]**, [pause]
    text = re.sub(r"\*{0,3}\[[^\]]*\]\*{0,3}", "", text)
    # Headings (leading #), and horizontal-rule lines (---, ***, ___)
    text = re.sub(r"(?m)^\s{0,3}#{1,6}\s*", "", text)
    text = re.sub(r"(?m)^\s*([-*_])\1{2,}\s*$", "", text)
    # List markers at the start of a line (-, *, +, "1.")
    text = re.sub(r"(?m)^\s*(?:[-*+]|\d+\.)\s+", "", text)
    # Bold/italic emphasis — keep the words, drop the markers
    text = re.sub(r"\*{1,3}([^*\n]+?)\*{1,3}", r"\1", text)
    text = re.sub(r"_{1,3}([^_\n]+?)_{1,3}", r"\1", text)
    text = text.replace("**", "").replace("__", "")
    # Tidy whitespace: no leading/trailing spaces per line, at most one blank line
    # between paragraphs (the player renders with white-space: pre-wrap)
    text = re.sub(r"(?m)^[ \t]+", "", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

# We talk to OpenRouter's OpenAI-compatible Chat Completions endpoint. Any provider
# that speaks that format (OpenRouter, OpenAI, local vLLM, …) works by changing the
# base URL + key + model, with no code change.
API_KEY = os.environ["OPENROUTER_API_KEY"]
BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
MODEL = os.getenv("LLM_MODEL", "meta-llama/llama-3.3-70b-instruct:free")


def _complete(system: str, user: str, max_tokens: int = 1500) -> str:
    resp = requests.post(
        f"{BASE_URL}/chat/completions",
        headers={
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": MODEL,
            "max_tokens": max_tokens,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        },
        timeout=120,
    )
    resp.raise_for_status()
    return (resp.json()["choices"][0]["message"]["content"] or "").strip()


def _addressing(user_name: str | None) -> str:
    """One instruction line telling the model how to address the worshipper.

    Named worshippers are greeted personally. Anonymous ones (guests who declined to
    give a name) must never be addressed by name — and the model must not invent one
    either; it speaks to them warmly without using any name at all."""
    name = (user_name or "").strip()
    if name:
        return f"Address the worshipper personally by name; their name is {name}."
    return (
        "The worshipper is anonymous: do NOT address them by name and do NOT invent "
        "one. Speak to them warmly without using any name."
    )


def build_intake_plan(*, user_name: str | None, mood: str, prayer_text: str | None) -> dict:
    """
    First pass: derive the service's spine from the user input.
    Returns scripture reference, a Suno music prompt, and a YouTube search query.
    """
    system = (
        "You are the Liturgical Context Engine for a personalized worship service. "
        "Stay within mainstream historical Christian theology: grace, hope, redemption, "
        "community. Avoid politics and fringe doctrine. Output ONLY valid JSON, no prose, "
        "no markdown fences."
    )
    user = json.dumps({
        "user_name": user_name or "",
        "mood": mood,
        "prayer_text": prayer_text or "",
        "schema": {
            "scripture_ref": "string, e.g. 'Psalm 23:1-4'",
            "music_prompt": "string, a prompt for AI worship-music generation",
            "music_query": "string, a short YouTube search query for a worship song",
            "preaching_query": "string, a short YouTube search query for a Christian sermon on this theme",
        },
    })
    raw = _complete(system, user, max_tokens=400).strip()
    raw = raw.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    return json.loads(raw)


def generate_welcome(*, user_name: str | None, mood: str) -> str:
    """
    A short "welcome back" greeting shown on the countdown screen while the rest of
    the service is still composing. Tuned to the feeling the worshipper chose, it is
    spoken-style and deliberately brief — it is read in a few seconds, not preached.
    """
    system = (
        "You are the warm voice that welcomes a returning worshipper back to their "
        "personal worship service. Write a SHORT greeting (40-70 words) that opens by "
        "welcoming them and gently meets the feeling they arrived with — "
        "comfort if they are anxious or grieving, shared joy if grateful or joyful, "
        "encouragement if seeking or hopeful. Spoken cadence, one short paragraph, no "
        "headings, no scripture citation. Stay within mainstream Christian hope and grace."
    )
    user = f"{_addressing(user_name)}\nFeeling they chose today: {mood}"
    return _strip_formatting(_complete(system, user, max_tokens=180))


def generate_opening_prayer(*, user_name: str | None, mood: str, prayer_text: str | None) -> str:
    system = (
        "You are a warm, pastoral voice opening a worship service. Write a personalized "
        "opening prayer (120-180 words) that gently acknowledges the person's situation "
        "without exposing sensitive detail bluntly. Spoken cadence, no headings."
    )
    user = (
        f"{_addressing(user_name)}\nMood: {mood}\n"
        f"What they shared: {prayer_text or '(nothing specific)'}"
    )
    return _strip_formatting(_complete(system, user, max_tokens=500))


def generate_sermon(*, user_name: str | None, mood: str, scripture_ref: str, target_minutes: int = 8) -> str:
    """Preaching segment, built around the user's mood and the chosen passage."""
    system = (
        "You are an expository preacher writing for spoken delivery by a digital avatar. "
        "Move through three movements — a hook that draws the listener in, the passage's "
        "context and meaning, then how it applies to their life today — but write it as "
        f"one continuous spoken message. Target {target_minutes} minutes (~130-150 "
        "words/min). Plain spoken prose ONLY: no headings, no section labels, no bullet "
        "points, no markdown (no #, *, _, ---), and no stage directions or bracketed cues "
        "of any kind. If the theme touches a serious medical or safety emergency, do not "
        "advise; close gently and defer to real-world help."
    )
    user = (
        f"Scripture focus: {scripture_ref}\n"
        f"Listener's theme/mood: {mood}\n"
        f"{_addressing(user_name)}"
    )
    return _strip_formatting(_complete(system, user, max_tokens=2500))


def generate_benediction(*, user_name: str | None, mood: str) -> str:
    system = (
        "Write a short closing benediction (50-90 words) for spoken delivery. Personal, "
        "hopeful, sends the listener out with peace. No headings."
    )
    user = f"{_addressing(user_name)}\nMood: {mood}"
    return _strip_formatting(_complete(system, user, max_tokens=250))
