"""
LLM engine — turns the logged-in user's intake (name, mood, prayer text) into the
spoken content of the service: opening prayer, scripture selection, sermon, and
benediction. The user's own words drive every segment, so no two services match.

Scripture text is NOT generated by the model (copyright + accuracy). The model only
chooses a reference; full verse text is resolved separately via a licensed Bible API.
"""

from __future__ import annotations

import json
import os
import re

import requests


def _strip_formatting(text: str) -> str:
    """Reduce model output to clean spoken prose.

    Free models tend to dress a sermon up as a *script* — markdown headings, bold,
    bullet lists, horizontal rules, and bracketed stage directions like
    ``**[Soft instrumental intro]**`` or ``[Pause - 3 seconds]``. None of that should
    be shown to (or read aloud to) the worshipper, so we strip it here, leaving the
    words. Applied to every spoken segment, so the prompt and the model can't leak
    formatting into the service."""
    # Stage directions / cues in brackets, with any wrapping emphasis: **[...]**, [pause]
    text = re.sub(r"\*{0,3}\[[^\]]*\]\*{0,3}", "", text)
    # Headings (leading #), and horizontal-rule lines (---, ***, ___)
    text = re.sub(r"(?m)^\s{0,3}#{1,6}\s*", "", text)
    text = re.sub(r"(?m)^\s*([-*_])\1{2,}\s*$", "", text)
    # List markers at the start of a line (-, *, +, "1.")
    text = re.sub(r"(?m)^\s*(?:[-*+]|\d+\.)\s+", "", text)
    # Bold/italic emphasis — keep the words, drop the markers
    text = re.sub(r"\*{1,3}([^*\n]+?)\*{1,3}", r"\1", text)
    text = re.sub(r"_{1,3}([^_\n]+?)_{1,3}", r"\1", text)
    text = text.replace("**", "").replace("__", "")
    # Tidy whitespace: no leading/trailing spaces per line, at most one blank line
    # between paragraphs (the player renders with white-space: pre-wrap)
    text = re.sub(r"(?m)^[ \t]+", "", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _strip_name(text: str, user_name: str | None) -> str:
    """Safety net: scrub the worshipper's name out of generated prose.

    The prompt tells the model not to address the listener by name, but free models
    slip and drop it in anyway (``"Test Admin, imagine..."``). For segments that must
    never expose the name (the sermon/message), we also remove any literal occurrence
    of it — the full name and each of its words — and repair the punctuation/casing
    left behind by a removed vocative."""
    name = (user_name or "").strip()
    if not name:
        return text
    # Full name first, then each word (longest-first so "Test Admin" beats "Test").
    parts = [p for p in re.split(r"\s+", name) if len(p) >= 2]
    for cand in sorted({name, *parts}, key=len, reverse=True):
        c = re.escape(cand)
        # Opening vocative — "Name, imagine ..." -> "Imagine ..." (recapitalize).
        text = re.sub(
            rf"(?m)(?:^|(?<=[.!?]\s)){c}\s*,\s*(\w)",
            lambda m: m.group(1).upper(),
            text,
        )
        # Trailing/inline vocative — ", Name." / ", Name," -> drop the name.
        text = re.sub(rf",\s*{c}\b", "", text)
        # Any remaining standalone mention.
        text = re.sub(rf"\b{c}\b", "", text)
    # Tidy spacing and orphaned punctuation left by the removals.
    text = re.sub(r"\s+([,.!?;:])", r"\1", text)
    text = re.sub(r"[ \t]{2,}", " ", text)
    return text.strip()

# We talk to OpenRouter's OpenAI-compatible Chat Completions endpoint. Any provider
# that speaks that format (OpenRouter, OpenAI, local vLLM, …) works by changing the
# base URL + key + model, with no code change.
API_KEY = os.environ["OPENROUTER_API_KEY"]
BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
MODEL = os.getenv("LLM_MODEL", "meta-llama/llama-3.3-70b-instruct:free")


def _complete(system: str, user: str, max_tokens: int = 1500) -> str:
    resp = requests.post(
        f"{BASE_URL}/chat/completions",
        headers={
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": MODEL,
            "max_tokens": max_tokens,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        },
        timeout=120,
    )
    resp.raise_for_status()
    return (resp.json()["choices"][0]["message"]["content"] or "").strip()


def _addressing(user_name: str | None) -> str:
    """One instruction line telling the model how to address the worshipper.

    Named worshippers are greeted personally. Anonymous ones (guests who declined to
    give a name) must never be addressed by name — and the model must not invent one
    either; it speaks to them warmly without using any name at all."""
    name = (user_name or "").strip()
    if name:
        return f"Address the worshipper personally by name; their name is {name}."
    return (
        "The worshipper is anonymous: do NOT address them by name and do NOT invent "
        "one. Speak to them warmly without using any name."
    )


def _language_instruction(language: str) -> str:
    """One system-prompt line fixing the output language of a spoken segment.

    'my' services are conducted entirely in Burmese. The instruction pins the
    script too — Myanmar Unicode only, never Zawgyi or romanization — because the
    player renders with Unicode fonts (Padauk/Noto Sans Myanmar) and edge-tts's
    my-MM voices expect Unicode text.

    'td' services are conducted in Tedim Chin (Zolai / Zomi pau, Latin script).
    The instruction anchors the model with the community's own Christian
    register — Pasian (God), Topa (the Lord), Zeisu (Jesus) — the vocabulary of
    the Lai Siangtho (1932) and the ZBC hymnal, which the scripture and hymn
    segments already use."""
    if language == "my":
        return (
            "Write your ENTIRE response in the Burmese (Myanmar) language, using "
            "Myanmar Unicode script only (never Zawgyi, never romanized Burmese, "
            "no English words). Use natural, reverent Burmese as spoken in a "
            "Christian worship service."
        )
    if language == "td":
        return (
            "Write your ENTIRE response in the Tedim Chin language (Zolai / Zomi "
            "pau), in its standard Latin orthography — no English sentences, no "
            "Burmese script. Use the natural, reverent register of a Zomi "
            "Christian worship service, with the community's established terms: "
            "Pasian for God, Topa for the Lord, Zeisu for Jesus, Kha Siangtho "
            "for the Holy Spirit, thungetna for prayer. Keep sentences short and "
            "clear; if a precise Tedim word is uncertain, choose simpler Tedim "
            "rather than borrowing English."
        )
    return ""


def build_intake_plan(*, user_name: str | None, mood: str, prayer_text: str | None, language: str = "en") -> dict:
    """
    First pass: derive the service's spine from the user input.
    Returns scripture reference, a Suno music prompt, and a YouTube search query.
    """
    system = (
        "You are the Liturgical Context Engine for a personalized worship service. "
        "Stay within mainstream historical Christian theology: grace, hope, redemption, "
        "community. Avoid politics and fringe doctrine. Output ONLY valid JSON, no prose, "
        "no markdown fences."
    )
    if language == "my":
        # The scripture reference is part of the worker contract (bible_api parses
        # English references and serves the Judson 1835 Burmese text), so it stays
        # English; the music prompt and search queries face Burmese providers/users.
        system += (
            " This service is conducted in the Burmese (Myanmar) language. Keep "
            "scripture_ref in ENGLISH format (e.g. 'Psalm 23:1-4'), but write "
            "music_prompt for a Burmese-language worship song, and make music_query "
            "and preaching_query searches for Burmese (Myanmar) Christian content."
        )
    elif language == "td":
        system += (
            " This service is conducted in the Tedim Chin (Zomi) language. Keep "
            "scripture_ref in ENGLISH format (e.g. 'Psalm 23:1-4'), but write "
            "music_prompt for a Tedim/Zomi-language worship song, and make "
            "music_query and preaching_query searches for Zomi or Tedim Chin "
            "Christian content."
        )
    user = json.dumps({
        "user_name": user_name or "",
        "mood": mood,
        "prayer_text": prayer_text or "",
        "schema": {
            "scripture_ref": "string, e.g. 'Psalm 23:1-4'",
            "music_prompt": "string, a prompt for AI worship-music generation",
            "music_query": "string, a short YouTube search query for a worship song",
            "preaching_query": "string, a short YouTube search query for a Christian sermon on this theme",
        },
    })
    raw = _complete(system, user, max_tokens=400).strip()
    raw = raw.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
    return json.loads(raw)


def generate_welcome(*, user_name: str | None, mood: str, language: str = "en") -> str:
    """
    A short "welcome back" greeting shown on the countdown screen while the rest of
    the service is still composing. Tuned to the feeling the worshipper chose, it is
    spoken-style and deliberately brief — it is read in a few seconds, not preached.
    """
    system = (
        "You are the warm voice that welcomes a returning worshipper back to their "
        "personal worship service. Write a SHORT greeting (40-70 words) that opens by "
        "welcoming them and gently meets the feeling they arrived with — "
        "comfort if they are anxious or grieving, shared joy if grateful or joyful, "
        "encouragement if seeking or hopeful. Spoken cadence, one short paragraph, no "
        "headings, no scripture citation. Stay within mainstream Christian hope and grace."
    )
    if language != "en":
        system = f"{system} {_language_instruction(language)}"
    user = f"{_addressing(user_name)}\nFeeling they chose today: {mood}"
    return _strip_formatting(_complete(system, user, max_tokens=180))


def generate_opening_prayer(*, user_name: str | None, mood: str, prayer_text: str | None, language: str = "en") -> str:
    system = (
        "You are a warm, pastoral voice opening a worship service. Write a personalized "
        "opening prayer (120-180 words) that gently acknowledges the person's situation "
        "without exposing sensitive detail bluntly. Spoken cadence, no headings."
    )
    if language != "en":
        system = f"{system} {_language_instruction(language)}"
    user = (
        f"{_addressing(user_name)}\nMood: {mood}\n"
        f"What they shared: {prayer_text or '(nothing specific)'}"
    )
    return _strip_formatting(_complete(system, user, max_tokens=500))


def generate_sermon(*, user_name: str | None, mood: str, scripture_ref: str, target_minutes: int = 8, language: str = "en") -> str:
    """Preaching segment, built around the user's mood and the chosen passage."""
    system = (
        "You are an expository preacher writing for spoken delivery by a digital avatar. "
        "Move through three movements — a hook that draws the listener in, the passage's "
        "context and meaning, then how it applies to their life today — but write it as "
        f"one continuous spoken message. Target {target_minutes} minutes (~130-150 "
        "words/min). Plain spoken prose ONLY: no headings, no section labels, no bullet "
        "points, no markdown (no #, *, _, ---), and no stage directions or bracketed cues "
        "of any kind. If the theme touches a serious medical or safety emergency, do not "
        "advise; close gently and defer to real-world help."
    )
    if language != "en":
        system = f"{system} {_language_instruction(language)}"
    user = (
        f"Scripture focus: {scripture_ref}\n"
        f"Listener's theme/mood: {mood}\n"
        "Do NOT address the listener by name and do NOT invent one — never write any "
        "personal name for them anywhere in the message. Speak to them warmly using "
        "only 'you'."
    )
    text = _strip_formatting(_complete(system, user, max_tokens=2500))
    return _strip_name(text, user_name)


def generate_benediction(*, user_name: str | None, mood: str, language: str = "en") -> str:
    system = (
        "Write a short closing benediction (50-90 words) for spoken delivery. Personal, "
        "hopeful, sends the listener out with peace. No headings."
    )
    if language != "en":
        system = f"{system} {_language_instruction(language)}"
    user = f"{_addressing(user_name)}\nMood: {mood}"
    return _strip_formatting(_complete(system, user, max_tokens=250))
