"""
LLM engine — turns the logged-in user's intake (name, mood, prayer text) into the
spoken content of the service: opening prayer, scripture selection, sermon, and
benediction. The user's own words drive every segment, so no two services match.

Scripture text is NOT generated by the model (copyright + accuracy). The model only
chooses a reference; full verse text is resolved separately via a licensed Bible API.
"""

from __future__ import annotations

import json
import os
import re

import requests


_TEDIM_CORRECTIONS = [
    # Mizo word       → Tedim word      (word-boundary, case-insensitive)
    (r"\bkohhran\b",   "koici"),        # church
    (r"\btawngtaina\b","thungetna"),    # prayer (noun)
    (r"\btawngtai\b",  "thungeta"),     # pray (verb)
    (r"\bpathian\b",   "Pasian"),       # God
    (r"\blalpa\b",     "Topa"),         # the Lord
    (r"\bisua\b",      "Zeisu"),        # Jesus
]
_TEDIM_CORRECTIONS_COMPILED = [
    (re.compile(pat, re.IGNORECASE), rep) for pat, rep in _TEDIM_CORRECTIONS
]


def _fix_tedim_vocab(text: str) -> str:
    for pattern, replacement in _TEDIM_CORRECTIONS_COMPILED:
        text = pattern.sub(replacement, text)
    return text


def _strip_formatting(text: str) -> str:
    """Reduce model output to clean spoken prose.

    Free models tend to dress a sermon up as a *script* — markdown headings, bold,
    bullet lists, horizontal rules, and bracketed stage directions like
    ``**[Soft instrumental intro]**`` or ``[Pause - 3 seconds]``. None of that should
    be shown to (or read aloud to) the worshipper, so we strip it here, leaving the
    words. Applied to every spoken segment, so the prompt and the model can't leak
    formatting into the service."""
    # Stage directions / cues in brackets, with any wrapping emphasis: **[...]**, [pause]
    text = re.sub(r"\*{0,3}\[[^\]]*\]\*{0,3}", "", text)
    # Headings (leading #), and horizontal-rule lines (---, ***, ___)
    text = re.sub(r"(?m)^\s{0,3}#{1,6}\s*", "", text)
    text = re.sub(r"(?m)^\s*([-*_])\1{2,}\s*$", "", text)
    # List markers at the start of a line (-, *, +, "1.")
    text = re.sub(r"(?m)^\s*(?:[-*+]|\d+\.)\s+", "", text)
    # Bold/italic emphasis — keep the words, drop the markers
    text = re.sub(r"\*{1,3}([^*\n]+?)\*{1,3}", r"\1", text)
    text = re.sub(r"_{1,3}([^_\n]+?)_{1,3}", r"\1", text)
    text = text.replace("**", "").replace("__", "")
    # Tidy whitespace: no leading/trailing spaces per line, at most one blank line
    # between paragraphs (the player renders with white-space: pre-wrap)
    text = re.sub(r"(?m)^[ \t]+", "", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _strip_name(text: str, user_name: str | None) -> str:
    """Safety net: scrub the worshipper's name out of generated prose.

    The prompt tells the model not to address the listener by name, but free models
    slip and drop it in anyway (``"Test Admin, imagine..."``). For segments that must
    never expose the name (the sermon/message), we also remove any literal occurrence
    of it — the full name and each of its words — and repair the punctuation/casing
    left behind by a removed vocative."""
    name = (user_name or "").strip()
    if not name:
        return text
    # Full name first, then each word (longest-first so "Test Admin" beats "Test").
    parts = [p for p in re.split(r"\s+", name) if len(p) >= 2]
    for cand in sorted({name, *parts}, key=len, reverse=True):
        c = re.escape(cand)
        # Opening vocative — "Name, imagine ..." -> "Imagine ..." (recapitalize).
        text = re.sub(
            rf"(?m)(?:^|(?<=[.!?]\s)){c}\s*,\s*(\w)",
            lambda m: m.group(1).upper(),
            text,
        )
        # Trailing/inline vocative — ", Name." / ", Name," -> drop the name.
        text = re.sub(rf",\s*{c}\b", "", text)
        # Any remaining standalone mention.
        text = re.sub(rf"\b{c}\b", "", text)
    # Tidy spacing and orphaned punctuation left by the removals.
    text = re.sub(r"\s+([,.!?;:])", r"\1", text)
    text = re.sub(r"[ \t]{2,}", " ", text)
    return text.strip()


def _ensure_exact_name(text: str, user_name: str | None) -> str:
    """No-op: names are never injected into service output."""
    return text


# We talk to OpenRouter's OpenAI-compatible Chat Completions endpoint. Any provider
# that speaks that format (OpenRouter, OpenAI, local vLLM, …) works by changing the
# base URL + key + model, with no code change.
API_KEY = os.environ["OPENROUTER_API_KEY"]
BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
MODEL = os.getenv("LLM_MODEL", "meta-llama/llama-3.3-70b-instruct:free")
LOCAL_LLM_TIMEOUT = int(os.getenv("LOCAL_LLM_TIMEOUT", "300"))


def _model_for(language: str = "en") -> str:
    """Allow stronger models for low-resource service languages.

    Some free English-first models emit Burmese-looking text that is not natural
    Myanmar. Operators can set LLM_MODEL_MY or LLM_MODEL_TD without changing the
    English service model. Placeholder/example values are ignored so a copied
    .env cannot break generation with an invalid OpenRouter model id.
    """
    override = (os.getenv(f"LLM_MODEL_{language.upper()}") or "").strip()
    if override and not override.startswith(("your-", "change-me", "example")):
        return override
    return MODEL


def _local_llm_url(language: str) -> tuple[str, str] | None:
    if language == "my":
        base = (os.getenv("BURMESE_LLM_URL") or "").rstrip("/")
        return (base, "/burmese/generate") if base else None
    if language == "td":
        base = (os.getenv("TEDIM_LLM_URL") or "").rstrip("/")
        return (base, "/tedim/generate") if base else None
    return None


def _should_use_local_llm(system: str, language: str) -> bool:
    # The intake plan must stay on the chat model because it is a strict JSON
    # contract. Local low-resource generators are used for prose segments only.
    return language in ("my", "td") and "Output ONLY valid JSON" not in system


def _complete_local(system: str, user: str, max_tokens: int, language: str) -> str:
    endpoint = _local_llm_url(language)
    if not endpoint:
        raise RuntimeError(f"No local LLM URL configured for language {language!r}")
    base, path = endpoint
    resp = requests.post(
        f"{base}{path}",
        json={"system": system, "prompt": user, "max_tokens": max_tokens},
        timeout=LOCAL_LLM_TIMEOUT,
    )
    resp.raise_for_status()
    return (resp.json().get("text") or "").strip()


def _complete(system: str, user: str, max_tokens: int = 1500, language: str = "en") -> str:
    if _should_use_local_llm(system, language):
        text = _complete_local(system, user, max_tokens, language)
        if language == "td":
            text = _fix_tedim_vocab(text)
        return text

    resp = requests.post(
        f"{BASE_URL}/chat/completions",
        headers={
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
        },
        json={
            "model": _model_for(language),
            "max_tokens": max_tokens,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
        },
        timeout=120,
    )
    resp.raise_for_status()
    text = (resp.json()["choices"][0]["message"]["content"] or "").strip()
    if language == "td":
        text = _fix_tedim_vocab(text)
    return text


def _addressing(user_name: str | None) -> str:
    """Always address the worshipper anonymously — names are never used in output."""
    return (
        "Do NOT address the worshipper by name and do NOT invent one. "
        "Speak to them warmly without using any name."
    )


def _freshness_directive(user_history: dict | None) -> str:
    """Build a system-prompt clause that prevents repeating past service content.

    The worker passes the user's last ~10 sessions (same language) so the LLM
    can pick a different scripture passage, avoid recycled illustrations, and
    find fresh angles — ensuring every return visit feels genuinely new."""
    if not user_history:
        return ""
    parts = []
    past_refs = [r for r in (user_history.get("past_scripture_refs") or []) if r][:8]
    if past_refs:
        parts.append(
            "IMPORTANT — these Bible passages were already used in this person's past services; "
            f"choose a DIFFERENT passage: {', '.join(past_refs)}."
        )
    past_excerpts = [e for e in (user_history.get("past_prayer_excerpts") or []) if e][:4]
    if past_excerpts:
        parts.append(
            "Past prayer themes already addressed for this person: "
            + "; ".join(f'"{e}"' for e in past_excerpts)
            + ". Bring a genuinely fresh angle — a new illustration, metaphor, or facet "
            "of grace not yet explored."
        )
    return " ".join(parts)


def _keyword_anchor(prayer_text: str | None) -> str:
    """Surface the user's own feeling-words so the LLM grounds content in them.

    The prayer_text already flows into the user-turn prompt, but a short,
    clearly-labelled anchor phrase nudges the model to treat those exact words
    as the emotional centre of the segment rather than just context."""
    text = (prayer_text or "").strip()
    if not text:
        return ""
    snippet = text[:150].rsplit(" ", 1)[0] if len(text) > 150 else text
    return (
        f'The worshipper\'s own words: "{snippet}". '
        "Ground this segment directly in these specific feelings and concerns."
    )



def _fallback_opening_prayer(user_name: str | None, mood: str, language: str) -> str:
    if language == "my":
        return (
            "ကရုဏာတော်ရှင် ဘုရားသခင်၊ ယနေ့ ကိုယ်တော်ထံသို့ နီးကပ်စွာ ချဉ်းကပ်ပါသည်။ "
            "ဝမ်းနည်းခြင်း၊ ပင်ပန်းခြင်း၊ မတည်ငြိမ်ခြင်းများရှိနေပါက ကိုယ်တော်၏ ငြိမ်သက်ခြင်းဖြင့် ဖုံးလွှမ်းပေးပါ။ "
            "ကျွန်ုပ်တို့၏နှလုံးကို နားထောင်တတ်သော နှလုံးဖြစ်စေပြီး၊ သမ္မာတရား၏ အလင်းကို မြင်နိုင်စေပါ။ "
            "ယခု ဝတ်ပြုချိန်တွင် စကားလုံးတိုင်း၊ ဆုတောင်းခြင်းတိုင်း၊ သီချင်းတိုင်းသည် မျှော်လင့်ခြင်းနှင့် ယုံကြည်ခြင်းကို ပြန်လည်ထူထောင်စေပါ။ "
            "ယေရှုခရစ်တော်၏ နာမတော်၌ ဆုတောင်းပါသည်။ အာမင်။"
        )
    if language == "td":
        return (
            "Aw Topa Pasian, tuni in ka lungtang hong khol in na kiangah ka hong pai hi. "
            "Lungkhamna leh dahna om leh, na lungdamna leh na nopna in hong tuam in. "
            "Hih biakna hun sungah na Thu Siangtho in lam hong lak hen. "
            "Zeisu Krist min in ka thungen hi. Amen."
        )
    return "Lord, meet us with mercy and peace as this service begins. Amen."


def _fallback_sermon(mood: str, scripture_ref: str, language: str) -> str:
    if language == "my":
        try:
            import bible_api
            verse = bible_api.resolve(scripture_ref, lang="my")
            title = bible_api.book_title(scripture_ref, lang="my") or scripture_ref
        except Exception:
            verse = ""
            title = scripture_ref
        verse_line = f"{title} တွင် ဤသို့ သတိပေးထားပါသည်။ {verse} " if verse else "ဘုရားသခင်၏ သမ္မာတရားသည် ကျွန်ုပ်တို့ကို မျှော်လင့်ခြင်းထဲသို့ ပြန်ခေါ်ပါသည်။ "
        return (
            "ယနေ့ သင်၏နှလုံးသည် ဝမ်းနည်းခြင်းနှင့် ပင်ပန်းခြင်းကြားတွင် ရှိနေနိုင်ပါသည်။ "
            "သို့သော် ခရစ်တော်၏ သတင်းကောင်းသည် ကျွန်ုပ်တို့၏ ခံစားချက်ကို မငြင်းပယ်ဘဲ၊ ထိုနေရာထဲသို့ပင် မေတ္တာတော်ဖြင့် ဝင်လာသည်ဟု သွန်သင်ပါသည်။ "
            + verse_line +
            "ဤစကားသည် နာကျင်နေသောသူအတွက် ဘုရားသခင်သည် ဝေးကွာနေသူ မဟုတ်ကြောင်း ပြောနေပါသည်။ "
            "နှလုံးကြေကွဲသောအချိန်တွင် ကိုယ်တော်သည် နီးတော်မူသည်။ စကားမပြောနိုင်သော ဆုတောင်းခြင်းကိုပင် ကိုယ်တော် နားထောင်တော်မူသည်။ "
            "ထို့ကြောင့် ယနေ့ သင်သည် အားကြီးနေစရာ မလိုပါ။ ကိုယ်တော်ရှေ့တွင် ရိုးသားစွာ ရပ်နိုင်ပါသည်။ "
            "ခြေလှမ်းသေးသေးတစ်လှမ်းဖြင့် စတင်ပါ။ အသက်ရှူပါ။ ကိုယ်တော်၏ ကရုဏာတော်သည် ယနေ့အတွက် လုံလောက်သည်ဟု ယုံကြည်ပါ။ "
            "ဘုရားသခင်သည် သင့်ကို မေ့ထားတော်မမူ။ သင့်ဝမ်းနည်းခြင်းသည် နောက်ဆုံးစကား မဟုတ်ပါ။ ခရစ်တော်၌ မျှော်လင့်ခြင်းသည် ပြန်လည်ထွန်းလင်းနိုင်ပါသည်။"
        )
    if language == "td":
        return (
            "Tuni in na lungtang a dah leh a gim mahmah thei hi. Ahihhang Topa Pasian in na kiang pan gamla om lo hi. "
            "Thu Siangtho in, Topa in lungkiam mite kiangah nai hi ci in hong theisak hi. "
            "Na thugen zawhloh thungetna zong Topa in za hi. Tuni in thahat sak kul lo; Topa maiah diktak in ding thei hi. "
            "Zeisu Krist sungah lungdamna leh lam-etna om hi. Pasian in nang hong mangngilh lo hi."
        )
    return "God is near to the brokenhearted, and Christ gives hope for the next step."


def _fallback_benediction(user_name: str | None, mood: str, language: str) -> str:
    if language == "my":
        return (
            "ထာဝရဘုရား၏ ငြိမ်သက်ခြင်းသည် သင့်နှလုံးကို စောင့်ရှောက်ပါစေ။ "
            "ခရစ်တော်၏ မေတ္တာသည် သင့်ကို ချီးမြှောက်ပြီး၊ သန့်ရှင်းသောဝိညာဉ်တော်သည် သင်၏ နောက်ခြေလှမ်းကို လမ်းပြပါစေ။ "
            "ဝမ်းနည်းခြင်းအလယ်၌ပင် မျှော်လင့်ခြင်းကို တွေ့နိုင်ပါစေ။ အာမင်။"
        )
    if language == "td":
        return (
            "Topa Pasian nopna in na lungtang kem hen. "
            "Zeisu Krist itna in hong thahat sak hen, Kha Siangtho in na lam hong makaih hen. Amen."
        )
    return "May the peace of Christ guard your heart and guide your next step. Amen."


def _language_instruction(language: str) -> str:
    """One system-prompt line fixing the output language of a spoken segment.

    'my' services are conducted entirely in Burmese. The instruction pins the
    script too — Myanmar Unicode only, never Zawgyi or romanization — because the
    player renders with Unicode fonts (Padauk/Noto Sans Myanmar) and edge-tts's
    my-MM voices expect Unicode text.

    'td' services are conducted in Tedim Chin (Zolai / Zomi pau, Latin script).
    The instruction anchors the model with the community's own Christian
    register — Pasian (God), Topa (the Lord), Zeisu (Jesus) — the vocabulary of
    the Lai Siangtho (1932) and the ZBC hymnal, which the scripture and hymn
    segments already use."""
    if language == "my":
        return (
            "Write your ENTIRE response in the Burmese (Myanmar) language, using "
            "Myanmar Unicode script only (never Zawgyi, never romanized Burmese, "
            "no English words, except a worshipper's proper name when one is provided). "
            "Compose directly in natural Myanmar Burmese; do not translate English "
            "idioms word-for-word. Use simple, meaningful sentences and a reverent "
            "Christian worship register that ordinary Myanmar readers can understand. "
            "For narration, spell out numbers and Bible references in Burmese words; "
            "do not leave raw forms like 'Jn 3:16' or '2026'."
        )
    if language == "td":
        return (
            "LANGUAGE LAW — ABSOLUTE: Write EVERY SINGLE SENTENCE in Tedim Chin (Zolai / Zomi pau) ONLY. "
            "ZERO English sentences, ZERO English paragraphs, ZERO English explanations. "
            "Do NOT translate, do NOT add English alongside Tedim, do NOT explain in English. "
            "Every word must be Tedim. The only Latin letters allowed are Tedim words. "
            "Use standard Tedim Latin orthography only — no Burmese script. "
            "CRITICAL: Tedim is NOT Mizo, NOT Falam Chin, and NOT Haka Chin. Do NOT use Mizo words. "
            "These Tedim words are REQUIRED — use them exactly: "
            "Pasian (God) — NOT Pathian; "
            "Topa (the Lord) — NOT Lal or Lalpa; "
            "Zeisu Krist (Jesus Christ) — NOT Isua; "
            "Kha Siangtho (Holy Spirit); "
            "thungetna (prayer) — NOT tawngtaina; "
            "koici (church) — NOT kohhran; "
            "zangtal (salvation); "
            "lungdamna (grace/blessing); "
            "Thu Siangtho (Holy Scripture); "
            "Siangtho (holy/sacred); "
            "Zomi (the Tedim people). "
            "Tedim declarative sentences end with 'hi'; benedictive endings use 'hen'. "
            "Common Tedim sentence patterns: 'Pasian in i hiam hi' (God loves you), "
            "'Topa in na ngaih hi' (the Lord hears you), 'Zeisu in zangtal piak hi' (Jesus gives salvation). "
            "Keep sentences short and clear. Compose directly in Tedim; never translate English idioms. "
            "For narration, spell out numbers and Bible references in Tedim words; do not leave raw forms like 'Jn 3:16' or '2026'."
        )
    return ""


def _fallback_music_lyrics(mood: str, language: str) -> str:
    """Guaranteed customMode lyrics for AI-composed worship when the plan omits them."""
    if language == "my":
        return (
            "[Verse 1]\n"
            "ကိုယ်တော်ရှင်၊ ယနေ့ ကျွန်ုပ်၏နှလုံးသားထဲသို့ ကြွလာပါ။\n"
            "ပင်ပန်းသောစိတ်ကို ငြိမ်သက်ခြင်းဖြင့် ဖေးမပါ။\n"
            "ကိုယ်တော်၏မေတ္တာသည် မကုန်ဆုံးသောအလင်းဖြစ်သည်။\n"
            "ယုံကြည်ခြင်းဖြင့် ကျွန်ုပ် ကိုယ်တော်ထံ ခိုလှုံပါသည်။\n\n"
            "[Chorus]\n"
            "ယေရှုဘုရား၊ ကိုယ်တော်ကို ချီးမွမ်းပါသည်။\n"
            "ကျေးဇူးတော်ထဲတွင် ကျွန်ုပ် အသက်ရှင်ပါသည်။\n"
            "လမ်းပြတော်မူပါ၊ ဖေးမတော်မူပါ။\n"
            "ကိုယ်တော်၏ငြိမ်သက်ခြင်းဖြင့် ကျွန်ုပ်ကို ပြည့်စေပါ။\n\n"
            "[Verse 2]\n"
            "မျှော်လင့်ခြင်းနည်းသောအချိန်တွင် ကိုယ်တော်သည် နီးပါသည်။\n"
            "ကြောက်ရွံ့ခြင်းထဲမှ ကျွန်ုပ်ကို လက်ကမ်းခေါ်ပါ။\n"
            "နေ့ရက်တိုင်းတွင် ကိုယ်တော်၏ကရုဏာကို မြင်စေပါ။\n"
            "ကျွန်ုပ်၏အသက်တာသည် ကိုယ်တော်အတွက် သီချင်းဖြစ်ပါစေ။"
        )
    if language == "td":
        _mood = (mood or "").lower()
        # Mood-appropriate Tedim fallback lyrics so the static fallback varies by feeling.
        if any(w in _mood for w in ("griev", "sad", "mourn", "loss", "broken", "sorr")):
            return (
                "[Verse 1]\n"
                "Topa, ka lungkim ngai khat mama hi.\n"
                "Lungkhamna sungah nang hong naih zel hi.\n"
                "Ka thil suah ding hi nang kianga hi.\n"
                "Na lungdamna in ka lungtang hong kem sak in.\n\n"
                "[Chorus]\n"
                "Topa aw, hong kem in, hong kem in.\n"
                "Ka lungkhamna sungah nang om zel hi.\n"
                "Ka siamna tawm ahihhang nang in ka za hi.\n"
                "Zeisu Krist, na itna in hong khen sak in.\n\n"
                "[Verse 2]\n"
                "Lauhna sungpan na khut in hong kai hi.\n"
                "Ka nuntakna hong makaih in hong kem in.\n"
                "Ni simin na hehpihna ka mu thei hi.\n"
                "Ka nuntakna in Nang ading lasa suak hen."
            )
        if any(w in _mood for w in ("joy", "grateful", "thankful", "celebrat", "nop")):
            return (
                "[Verse 1]\n"
                "Nopna tawh Topa na min hong phat hi.\n"
                "Na hehpihna mama hi, na lungdamna lian hi.\n"
                "Pasian, tuni na kianga hong pai hi.\n"
                "Na lungdamna sungah ka lungtang dim hi.\n\n"
                "[Chorus]\n"
                "Topa aw, ka phat ding hi nang.\n"
                "Na nopna in ka lungtang a dim hi.\n"
                "Zeisu Krist, na min phat ding hi.\n"
                "Na lungdamna sungah ka nungta hi.\n\n"
                "[Verse 2]\n"
                "Ni simin na kilemna ka mu hi.\n"
                "Ka nuntakna in Nang ading lasa suak hi.\n"
                "Pasian in hong hehpih zel hi.\n"
                "Ka nuntakna in Nang ading lasa suak hen."
            )
        # Default (anxious / seeking / general)
        return (
            "[Verse 1]\n"
            "Topa, tuni ka lungtang sungah hong om in.\n"
            "Ka lunggimna sungah na lungdamna in hong kem in.\n"
            "Pasian itna in khuavak bangin hong taang hi.\n"
            "Zeisu Krist tungah ka muang in ka bia hi.\n\n"
            "[Chorus]\n"
            "Topa aw, Nang kong phat hi.\n"
            "Na lungdamna sungah ka nungta hi.\n"
            "Hong makaih in, hong kem in.\n"
            "Na kilemna in ka lungtang hong dim sak in.\n\n"
            "[Verse 2]\n"
            "Lam-etna tawm hunah nang hong naih zel hi.\n"
            "Lauhna sungpan na khut in hong kai hi.\n"
            "Ni simin na hehpihna ka mu sak in.\n"
            "Ka nuntakna in Nang ading lasa suak hen."
        )
    return (
        "[Verse 1]\n"
        "Lord, meet me in this moment,\n"
        "With mercy kind and near.\n"
        "Lift my heart toward Your promise,\n"
        "And quiet every fear.\n\n"
        "[Chorus]\n"
        "I will worship, I will trust You,\n"
        "In Your grace I stand today.\n"
        "Jesus, lead me, Jesus, hold me,\n"
        "Guide my heart along Your way.\n\n"
        "[Verse 2]\n"
        "When hope feels small and distant,\n"
        "Your love is still my song.\n"
        "You are faithful in the waiting,\n"
        "And Your peace will make me strong."
    )


def _lyrics_match_language(lyrics: str, language: str) -> bool:
    """Lightweight guard so Suno customMode receives lyrics in the service language."""
    text = (lyrics or "").strip()
    if not text:
        return False
    lower = text.lower()
    if language == "my":
        return bool(re.search(r"[\u1000-\u109f]", text))
    if language == "td":
        # Reject common non-Tedim Chin worship terms that often indicate Mizo/Falam/Haka drift.
        forbidden_hits = sum(
            1
            for word in (
                "pathian", "lalpa", "isua", "kohhran", "tawngtaina", "tawngtai",
                "ka lawm e", "halleluiah", "i lawm e",
            )
            if word in lower
        )
        if forbidden_hits > 0:
            return False

        tedim_hits = sum(
            1
            for word in (
                "pasian", "topa", "zeisu", "krist", "lungdamna", "kilemna",
                "hehpihna", "nang", "hong", "ka ", "kong", "na ", "sungah",
                "tuni", "nuntakna", "lametna", "bia", "phat",
            )
            if word in lower
        )
        core_hits = sum(1 for word in ("pasian", "topa", "zeisu", "krist") if word in lower)
        english_hits = sum(
            1
            for word in (
                "lord", "jesus", "grace", "mercy", "worship", "trust",
                "heart", "promise", "fear", "peace", "love", "hope",
            )
            if word in lower
        )
        # Tedim declarative sentences end with "hi"; benedictive endings use "hen".
        # These are the most reliable Tedim-specific markers — Mizo and English never
        # use them as sentence-final particles. Count lines/phrases that end with them.
        terminal_tedim = (
            lower.count(" hi\n") + lower.count(" hi.")
            + lower.count(" hi!") + lower.count(" hen\n")
            + lower.count(" hen.") + lower.count(" hen!")
        )
        if lower.rstrip().endswith((" hi", " hen")):
            terminal_tedim += 1
        # The lyric body must clearly be Tedim/Zolai: sufficient vocabulary, the core
        # Zomi theological terms, no English worship words, and the unmistakable Tedim
        # sentence-final particles that prove the grammar is genuinely Zolai.
        return (
            tedim_hits >= 5
            and core_hits >= 2
            and english_hits == 0
            and terminal_tedim >= 2
        )
    return True


def build_intake_plan(*, user_name: str | None, mood: str, prayer_text: str | None, language: str = "en", music_source: str | None = None, user_history: dict | None = None) -> dict:
    """
    First pass: derive the service's spine from the user input.
    Returns scripture reference, a Suno music prompt, optional Suno custom-mode
    lyrics, and YouTube search queries.
    """
    system = (
        "You are the Liturgical Context Engine for a personalized worship service. "
        "Stay within mainstream historical Christian theology: grace, hope, redemption, "
        "community. Avoid politics and fringe doctrine. Output ONLY valid JSON, no prose, "
        "no markdown fences. music_lyrics is REQUIRED for every language and must be "
        "singable worship lyrics, not a description."
    )
    freshness = _freshness_directive(user_history)
    if freshness:
        system = f"{system} {freshness}"
    if language == "my":
        # The scripture reference is part of the worker contract (bible_api parses
        # English references and serves the Judson 1835 Burmese text), so it stays
        # English; the music prompt and search queries face Burmese providers/users.
        system += (
            " This service is conducted in the Burmese (Myanmar) language. Keep "
            "scripture_ref in ENGLISH format (e.g. 'Psalm 23:1-4'), but write "
            "music_prompt and music_lyrics for a Burmese-language worship song in Myanmar "
            "Unicode, and make music_query and preaching_query searches for Burmese "
            "(Myanmar) Christian content."
        )
    elif language == "td":
        system += (
            " This service is conducted in the Tedim Chin (Zolai / Zomi pau) language. Keep "
            "scripture_ref in ENGLISH format (e.g. 'Psalm 23:1-4'). "
            "music_lyrics will be supplied separately — set it to an empty string. "
            "Write music_prompt as a short English style description for AI music generation "
            "(e.g. 'Zomi/Tedim Christian worship, congregational choir, acoustic band'). "
            "Make music_query and preaching_query searches for Zomi or Tedim Chin Christian content."
        )
    user = json.dumps({
        "user_name": user_name or "",
        "mood": mood,
        "prayer_text": prayer_text or "",
        "schema": {
            "scripture_ref": "string, e.g. 'Psalm 23:1-4'",
            "music_prompt": "string, a short style prompt for AI worship-music generation",
            "music_lyrics": "string, original singable worship lyrics in the service language, {} and a chorus{}".format(
                "1 short verse" if music_source == "musicgen" else "2 short verses",
                "" if music_source == "musicgen" else ", using [Verse 1] / [Chorus] / [Verse 2] structural tags on their own lines",
            ),
            "music_query": "string, a short YouTube search query for a worship song",
            "preaching_query": "string, a short YouTube search query for a Christian sermon on this theme",
        },
    })
    try:
        raw = _complete(system, user, max_tokens=900, language=language).strip()
        raw = raw.removeprefix("```json").removeprefix("```").removesuffix("```").strip()
        plan = json.loads(raw)
    except Exception as exc:
        print(f"[llm] intake plan fallback for {language}: {exc}", flush=True)
        plan = {}

    plan.setdefault("scripture_ref", "Psalm 23:1-3")
    plan.setdefault("music_prompt", f"A reverent Christian worship song for someone feeling {mood}")
    if not _lyrics_match_language(str(plan.get("music_lyrics") or ""), language):
        plan["music_lyrics"] = _fallback_music_lyrics(mood, language)
    if language == "td":
        plan["music_prompt"] = (
            f"Modern contemporary Zomi/Tedim Christian worship song for someone feeling {mood}, "
            "in a live contemporary worship style with uplifting congregational energy, "
            "with warm choir and acoustic-band arrangement. Sing the provided Tedim lyrics exactly."
        )
    elif language == "my":
        plan["music_prompt"] = (
            f"Modern contemporary Burmese Christian worship song for someone feeling {mood}, "
            "in a live contemporary worship style with uplifting congregational energy, "
            "with warm choir and acoustic-band arrangement. Sing the provided Myanmar Unicode lyrics exactly."
        )
    else:
        plan["music_prompt"] = (
            f"Modern contemporary Christian worship song for someone feeling {mood}, "
            "in a live contemporary worship style with uplifting congregational energy, "
            "with warm choir and acoustic-band arrangement. Sing the provided lyrics exactly."
        )
    plan.setdefault("music_query", f"Christian worship song {mood}")
    plan.setdefault("preaching_query", f"Christian sermon {mood}")
    return plan


def generate_welcome(*, user_name: str | None, mood: str, language: str = "en") -> str:
    """
    A short "welcome back" greeting shown on the countdown screen while the rest of
    the service is still composing. Tuned to the feeling the worshipper chose, it is
    spoken-style and deliberately brief — it is read in a few seconds, not preached.
    """
    lang_inst = _language_instruction(language) if language != "en" else ""
    system = (
        (f"{lang_inst} " if lang_inst else "") +
        "You are the warm voice that welcomes a returning worshipper back to their "
        "personal worship service. Write a SHORT greeting (40-70 words) that opens by "
        "welcoming them and gently meets the feeling they arrived with — "
        "comfort if they are anxious or grieving, shared joy if grateful or joyful, "
        "encouragement if seeking or hopeful. Spoken cadence, one short paragraph, no "
        "headings, no scripture citation. Stay within mainstream Christian hope and grace."
    )
    user = f"{_addressing(user_name)}\nFeeling they chose today: {mood}"
    return _ensure_exact_name(
        _strip_formatting(_complete(system, user, max_tokens=180, language=language)),
        user_name,
    )


def generate_opening_prayer(*, user_name: str | None, mood: str, prayer_text: str | None, language: str = "en", user_history: dict | None = None) -> str:
    lang_inst = _language_instruction(language) if language != "en" else ""
    system = (
        (f"{lang_inst} " if lang_inst else "") +
        "You are a warm, pastoral voice opening a worship service. Write a personalized "
        "opening prayer (120-180 words) that gently acknowledges the person's situation "
        "without exposing sensitive detail bluntly. Spoken cadence, no headings."
    )
    freshness = _freshness_directive(user_history)
    if freshness:
        system = f"{system} {freshness}"
    user = (
        f"{_addressing(user_name)}\nMood: {mood}\n"
        f"What they shared: {prayer_text or '(nothing specific)'}"
    )
    if anchor := _keyword_anchor(prayer_text):
        user = f"{user}\n{anchor}"
    try:
        return _ensure_exact_name(
            _strip_formatting(_complete(system, user, max_tokens=500, language=language)),
            user_name,
        )
    except Exception as exc:
        if language in ("my", "td"):
            print(f"[llm] {language} opening prayer fallback: {exc}", flush=True)
            return _ensure_exact_name(_fallback_opening_prayer(user_name, mood, language), user_name)
        raise


def generate_sermon(*, user_name: str | None, mood: str, scripture_ref: str, target_minutes: int = 8, language: str = "en", prayer_text: str | None = None, user_history: dict | None = None) -> str:
    """Preaching segment, built around the user's mood and the chosen passage."""
    lang_inst = _language_instruction(language) if language != "en" else ""
    system = (
        (f"{lang_inst} " if lang_inst else "") +
        "You are an expository preacher writing for spoken delivery by a digital avatar. "
        "Move through three movements — a hook that draws the listener in, the passage's "
        "context and meaning, then how it applies to their life today — but write it as "
        f"one continuous spoken message. Target {target_minutes} minutes (~130-150 "
        "words/min). Plain spoken prose ONLY: no headings, no section labels, no bullet "
        "points, no markdown (no #, *, _, ---), and no stage directions or bracketed cues "
        "of any kind. If the theme touches a serious medical or safety emergency, do not "
        "advise; close gently and defer to real-world help."
    )
    freshness = _freshness_directive(user_history)
    if freshness:
        system = f"{system} {freshness}"
    user = (
        f"Scripture focus: {scripture_ref}\n"
        f"Listener's theme/mood: {mood}\n"
        "Do NOT address the listener by name and do NOT invent one — never write any "
        "personal name for them anywhere in the message. Speak to them warmly using "
        "only 'you'."
    )
    if anchor := _keyword_anchor(prayer_text):
        user = f"{user}\n{anchor}"
    # Local Myanmar/Tedim Ollama models on small CPU boxes are much slower than the
    # hosted English chat model. Keep those messages shorter so the text pages land
    # reliably and narration is not asked to synthesize an eight-minute segment.
    if language in ("my", "td"):
        max_tokens = 600 if target_minutes <= 5 else 900
    else:
        max_tokens = 1500 if target_minutes <= 5 else 2500
    try:
        text = _strip_formatting(_complete(system, user, max_tokens=max_tokens, language=language))
    except Exception as exc:
        if language in ("my", "td"):
            print(f"[llm] {language} sermon fallback: {exc}", flush=True)
            return _fallback_sermon(mood, scripture_ref, language)
        raise
    return _strip_name(text, user_name)


def generate_benediction(*, user_name: str | None, mood: str, language: str = "en", prayer_text: str | None = None, user_history: dict | None = None) -> str:
    lang_inst = _language_instruction(language) if language != "en" else ""
    system = (
        (f"{lang_inst} " if lang_inst else "") +
        "Write a short closing benediction (50-90 words) for spoken delivery. Personal, "
        "hopeful, sends the listener out with peace. No headings."
    )
    freshness = _freshness_directive(user_history)
    if freshness:
        system = f"{system} {freshness}"
    user = f"{_addressing(user_name)}\nMood: {mood}"
    if anchor := _keyword_anchor(prayer_text):
        user = f"{user}\n{anchor}"
    try:
        return _ensure_exact_name(
            _strip_formatting(_complete(system, user, max_tokens=250, language=language)),
            user_name,
        )
    except Exception as exc:
        if language in ("my", "td"):
            print(f"[llm] {language} benediction fallback: {exc}", flush=True)
            return _ensure_exact_name(_fallback_benediction(user_name, mood, language), user_name)
        raise


def generate_music_lyrics(*, mood: str, language: str) -> str:
    """Generate worship song lyrics via the local language-specific LLM.

    For Tedim and Burmese the local Ollama model produces text in the correct
    script and grammar. If the local service is unreachable, busy, or its output
    fails the language guard, falls back to mood-keyed curated Tedim/Burmese lyrics.
    For English (and any other language) this just returns the fallback directly —
    callers use plan['music_lyrics'] from OpenRouter for those.
    """
    if language not in ("td", "my"):
        return _fallback_music_lyrics(mood, language)

    if language == "td":
        system = (
            "You are a Tedim Chin (Zolai) Christian worship song composer. "
            "Write worship song lyrics ONLY in the Tedim/Zolai language. "
            "Every sentence MUST end with 'hi' (declarative) or 'hen' (benedictive). "
            "Required Tedim words: Pasian (God), Topa (Lord), Zeisu Krist (Jesus Christ), "
            "ka (I/my), na (your), nang (you), hong (come), in (subject marker), "
            "sungah (in/inside), lungdamna (grace), lungtang (heart), nuntakna (life). "
            "Do NOT use English, Mizo, Falam, or Haka words. "
            "Start each section with a Suno structural tag on its own line: "
            "[Verse 1], [Chorus], [Verse 2]. Output ONLY the tagged lyric sections — no explanations."
        )
        user = (
            f"Write 2 short verses and 1 chorus of a Tedim worship song "
            f"for someone feeling {mood}."
        )
    else:  # my
        system = (
            "You are a Myanmar (Burmese) Christian worship song composer. "
            "Write worship song lyrics ONLY in Myanmar Burmese using Myanmar Unicode script. "
            "Use: ဘုရားသခင် (God), ကိုယ်တော် (Lord), ယေရှုခရစ်တော် (Jesus Christ). "
            "Do NOT use English words or Zawgyi encoding. "
            "Start each section with a Suno structural tag on its own line: "
            "[Verse 1], [Chorus], [Verse 2]. Output ONLY the tagged lyric sections — no explanations."
        )
        user = (
            f"Write 2 short verses and 1 chorus of a Burmese worship song "
            f"for someone feeling {mood}."
        )

    try:
        raw = _complete_local(system, user, max_tokens=400, language=language)
        if language == "td":
            raw = _fix_tedim_vocab(raw)
        text = _strip_formatting(raw)
        if _lyrics_match_language(text, language):
            return text
        print(f"[llm] local {language} lyrics failed language guard, using fallback", flush=True)
    except Exception as exc:
        print(f"[llm] local {language} lyrics unavailable ({exc}), using fallback", flush=True)

    return _fallback_music_lyrics(mood, language)
